# The URL the site will be built for
base_url = "http://www.laeith.com"

# Used in RSS by default
title = "Laeith's Tapestry of Life"
description = "A blog about many things, including but not only: computer science, philosophy, economics, mathematics, foundational work"
# The default language, used in RSS
default_language = "en"
# Whether to generate a RSS feed automatically
generate_feed = true
# The number of articles to include in the RSS feed. Will include all items if
# not set (the default).
feed_limit = 20

# Which theme to use for the code highlighting.
highlight_theme = "solarized-light"
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# TODO: add rss
#feed_filename = "rss.xml"

# Whether to copy or hardlink files in static/ directory. Useful for sites
# whose static files are large. Note that for this to work, both static/ and
# output directory need to be on the same filesystem. Also, theme's static/
# files are always copies, regardles of this setting. False by default.
# hard_link_static = false

# The taxonomies to be rendered for that site and their configuration
# Example:
#     taxonomies = [
#       {name = "tags", rss = true}, # each tag will have its own RSS feed
#       {name = "tags", lang = "fr"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no RSS or pagination
#     ]
#
taxonomies = []

# The additional languages for that site
# Example:
#     languages = [
#       {code = "fr", rss = true}, # there will be a RSS feed for French content
#       {code = "fr", search = true}, # there will be a Search Index for French content
#       {code = "it"}, # there won't be a RSS feed for Italian content
#     ]
#
languages = []

[extra]
# Put all your custom variables here
author = "laeith"
subtitle = "weave until it hopefully makes sense"
copyright = "None"

katex_enable = true
